#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#----common files-----
mv -i "$HOME/.i3" "$HOME/.i3_old"
ln -i -s -v  -T "$dir/.i3"  "$HOME/.i3"
rm -i "$HOME/.vimrc"
ln -i -s -v  "$dir/.vimrc" "$HOME/.vimrc"
rm -i "$HOME/.bashrc"
ln -i -s -v  "$dir/.bashrc" "$HOME/.bashrc"
rm -i "$HOME/.newsbeuter/config"
ln -i -s -v  "$dir/.newsbeuter/config"  "$HOME/.newsbeuter/config"
rm -i "$HOME/.config/redshift.conf"
ln -i -s -v  "$dir/.config/redshift.conf"  "$HOME/.config/redshift.conf"
rm -i "$HOME/.config/mpv/input.conf"
ln -i -s -v  "$dir/.config/mpv/input.conf"  "$HOME/.config/mpv/input.conf" 
rm -i "$HOME/.config/mpv/mpv.conf"
ln -i -s -v  "$dir/.config/mpv/mpv.conf"  "$HOME/.config/mpv/mpv.conf" 
rm -i "$HOME/.config/ranger/rc.conf"
ln -i -s -v  "$dir/.config/ranger/rc.conf"  "$HOME/.config/ranger/rc.conf" 
rm -i "$HOME/.config/ranger/rifle.conf"
ln -i -s -v  "$dir/.config/ranger/rifle.conf"  "$HOME/.config/ranger/rifle.conf" 
rm -i "$HOME/.config/ranger/scope.sh"
ln -i -s -v  "$dir/.config/ranger/scope.sh"  "$HOME/.config/ranger/scope.sh" 
rm -i "$HOME/.config/ranger/.conkyr"
ln -i -s -v  "$dir/.conkyrc"  "$HOME/.conkyrc"
rm -i "$HOME/.Xresources"
ln -i -s -v  "$dir/.Xresources"  "$HOME/.Xresources"
